apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      prometheus:
        endpoint: "prometheus:9090"
      jaeger:
        endpoint: "jaeger:14250"
      logging:
        loglevel: debug
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [jaeger, logging]
        metrics:
          receivers: [otlp]
          exporters: [prometheus, logging]