apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    exporters:
      prometheus:
        endpoint: "0.0.0.0:9091"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [prometheus]