apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
  labels:
    app: otelcol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol
  template:
    metadata:
      labels:
        app: otelcol
    spec:
      containers:
        - name: otelcol
          image: "otel/opentelemetry-collector:latest"
          args:
            - "--config=/conf/collector.yaml"
          volumeMounts:
            - mountPath: /conf
              name: collector-config
          ports:
            - containerPort: 4317  # Para o gRPC
            - containerPort: 4318  # Para o HTTP
            - containerPort: 9091  # Para o Prometheus
      volumes:
        - name: collector-config
          configMap:
            name: collector-config
            items:
              - key: collector.yaml
                path: collector.yaml