apiVersion: v1
kind: Service
metadata:
  name: otelcol
spec:
  type: NodePort
  selector:
    app: otelcol
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
      nodePort: 30001  # Porta para acessar externamente
    - name: http
      port: 4318
      targetPort: 4318
      nodePort: 30002  # Porta para acessar externamente
    - name: metrics
      port: 9091
      targetPort: 9091
      nodePort: 30003  # Porta para acessar externamente