apiVersion: batch/v1
kind: Job
metadata:
  name: data-loader-job
spec:
  template:
    spec:
      containers:
      - name: data-loader
        image: data-loader:latest  # Nome da imagem local
        imagePullPolicy: Never  # Usa a imagem local, sem tentar baixar de um registro
        env:
        - name: MYSQL_HOST
          value: "mysql"  # Nome do serviço do MySQL no Kubernetes
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "senha123"
        - name: MYSQL_DATABASE
          value: "filmes_db"
      restartPolicy: Never
  backoffLimit: 2  # Número de tentativas em caso de falha