apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: python:3.12
        command: ["sh", "-c"]
        args:
          - "pip install pymysql && python /app/download_imdb.py"
        volumeMounts:
        - name: mysql-volume
          mountPath: /app
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "senha123"
      restartPolicy: Never
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
