# k8s/app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-test
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
      - name: app-test
        image: sua-imagem-da-app-test
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_SERVICE_NAME
          value: "app-test"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://opentelemetry-collector:4317"
