apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1  # Para produção, você provavelmente quer mais réplicas para alta disponibilidade
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper:latest  # Imagem do Zookeeper no Docker Hub
          ports:
            - containerPort: 2181  # Porta do Zookeeper
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"  # Porta onde o Zookeeper ficará escutando
