apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest  # Ou uma versão específica
          ports:
            - containerPort: 3000  # Porta padrão do Grafana
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"  # Defina uma senha de administrador para o Grafana
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana  # Persistência de dados do Grafana
      volumes:
        - name: grafana-storage
          emptyDir: {}  # Para persistência, pode configurar um volume do tipo PVC (Persistent Volume Claim)
