apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: LoadBalancer  # Expor via LoadBalancer (público) ou ClusterIP (privado)
  selector:
    app: grafana
  ports:
    - port: 80  # Porta do serviço exposto
      targetPort: 3000  # Porta interna do container do Grafana
